/**
 * ms-skill-simulator의 skillbook 데이터를 v2로 포트.
 *  - base64 아이콘(icon/iconDisabled/iconMouseover)·soundPath 제거 (데이터만)
 *  - 나머지 스킬 데이터(id/masterLevel/weapons/description/levelProperties/
 *    requiredSkillLevels/invisible)는 그대로 유지
 *  - src/data/skills/skillbooks/<code>.json 으로 저장
 *
 * 실행: node scripts/importSkills.mjs
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, '..', '..', 'ms-skill-simulator', 'src', 'data', 'skillbooks')
const OUT = join(HERE, '..', 'src', 'data', 'skills', 'skillbooks')

function stripSkill(s) {
  // 메인 아이콘(icon, PNG base64)은 UI용으로 유지. 비활성/마우스오버/사운드만 제거.
  const { iconDisabled, iconMouseOver, soundPath, ...rest } = s
  void iconDisabled; void iconMouseOver; void soundPath
  return rest
}

async function main() {
  await mkdir(OUT, { recursive: true })
  const files = (await readdir(SRC)).filter((f) => f.endsWith('.json'))
  let bytesBefore = 0, bytesAfter = 0
  for (const f of files) {
    const raw = await readFile(join(SRC, f), 'utf8')
    bytesBefore += raw.length
    const book = JSON.parse(raw)
    const out = {
      id: book.id,
      job: book.job,
      description: book.description,
      skills: (book.skills ?? []).map(stripSkill),
    }
    const str = JSON.stringify(out, null, 2) + '\n'
    bytesAfter += str.length
    await writeFile(join(OUT, f), str, 'utf8')
  }

  // 스킬북 코드별 정적 import 인덱스 자동 생성
  const codes = files.map((f) => Number(f.replace('.json', ''))).sort((a, b) => a - b)
  const imports = codes.map((c) => `import b${c} from './skillbooks/${c}.json'`).join('\n')
  const entries = codes.map((c) => `  ${c}: b${c} as unknown as IJobSkillBook,`).join('\n')
  const gen = `// AUTO-GENERATED by scripts/importSkills.mjs — 편집하지 말 것.\nimport type { IJobSkillBook } from './types'\n${imports}\n\n/** 스킬북 코드 → 스킬북 데이터 */\nexport const SKILLBOOKS: Record<number, IJobSkillBook> = {\n${entries}\n}\n`
  await writeFile(join(HERE, '..', 'src', 'data', 'skills', 'books.generated.ts'), gen, 'utf8')

  console.log(`포트 완료: ${files.length}개 | ${(bytesBefore / 1e6).toFixed(1)}MB → ${(bytesAfter / 1e6).toFixed(2)}MB (아이콘 제거)`)
  console.log('books.generated.ts 생성 완료')
}
main().catch((e) => { console.error(e); process.exit(1) })
