// AUTO-GENERATED by scripts/importSkills.mjs — 편집하지 말 것.
import type { IJobSkillBook } from './types'
import b100 from './skillbooks/100.json'
import b110 from './skillbooks/110.json'
import b111 from './skillbooks/111.json'
import b112 from './skillbooks/112.json'
import b120 from './skillbooks/120.json'
import b121 from './skillbooks/121.json'
import b122 from './skillbooks/122.json'
import b130 from './skillbooks/130.json'
import b131 from './skillbooks/131.json'
import b132 from './skillbooks/132.json'
import b200 from './skillbooks/200.json'
import b210 from './skillbooks/210.json'
import b211 from './skillbooks/211.json'
import b212 from './skillbooks/212.json'
import b220 from './skillbooks/220.json'
import b221 from './skillbooks/221.json'
import b222 from './skillbooks/222.json'
import b230 from './skillbooks/230.json'
import b231 from './skillbooks/231.json'
import b232 from './skillbooks/232.json'
import b300 from './skillbooks/300.json'
import b310 from './skillbooks/310.json'
import b311 from './skillbooks/311.json'
import b312 from './skillbooks/312.json'
import b320 from './skillbooks/320.json'
import b321 from './skillbooks/321.json'
import b322 from './skillbooks/322.json'
import b400 from './skillbooks/400.json'
import b410 from './skillbooks/410.json'
import b411 from './skillbooks/411.json'
import b412 from './skillbooks/412.json'
import b420 from './skillbooks/420.json'
import b421 from './skillbooks/421.json'
import b422 from './skillbooks/422.json'
import b500 from './skillbooks/500.json'
import b510 from './skillbooks/510.json'
import b511 from './skillbooks/511.json'
import b512 from './skillbooks/512.json'
import b520 from './skillbooks/520.json'
import b521 from './skillbooks/521.json'
import b522 from './skillbooks/522.json'
import b1100 from './skillbooks/1100.json'
import b1110 from './skillbooks/1110.json'
import b1111 from './skillbooks/1111.json'
import b1200 from './skillbooks/1200.json'
import b1210 from './skillbooks/1210.json'
import b1211 from './skillbooks/1211.json'
import b1300 from './skillbooks/1300.json'
import b1310 from './skillbooks/1310.json'
import b1311 from './skillbooks/1311.json'
import b1400 from './skillbooks/1400.json'
import b1410 from './skillbooks/1410.json'
import b1411 from './skillbooks/1411.json'
import b1500 from './skillbooks/1500.json'
import b1510 from './skillbooks/1510.json'
import b1511 from './skillbooks/1511.json'

/** 스킬북 코드 → 스킬북 데이터 */
export const SKILLBOOKS: Record<number, IJobSkillBook> = {
  100: b100 as unknown as IJobSkillBook,
  110: b110 as unknown as IJobSkillBook,
  111: b111 as unknown as IJobSkillBook,
  112: b112 as unknown as IJobSkillBook,
  120: b120 as unknown as IJobSkillBook,
  121: b121 as unknown as IJobSkillBook,
  122: b122 as unknown as IJobSkillBook,
  130: b130 as unknown as IJobSkillBook,
  131: b131 as unknown as IJobSkillBook,
  132: b132 as unknown as IJobSkillBook,
  200: b200 as unknown as IJobSkillBook,
  210: b210 as unknown as IJobSkillBook,
  211: b211 as unknown as IJobSkillBook,
  212: b212 as unknown as IJobSkillBook,
  220: b220 as unknown as IJobSkillBook,
  221: b221 as unknown as IJobSkillBook,
  222: b222 as unknown as IJobSkillBook,
  230: b230 as unknown as IJobSkillBook,
  231: b231 as unknown as IJobSkillBook,
  232: b232 as unknown as IJobSkillBook,
  300: b300 as unknown as IJobSkillBook,
  310: b310 as unknown as IJobSkillBook,
  311: b311 as unknown as IJobSkillBook,
  312: b312 as unknown as IJobSkillBook,
  320: b320 as unknown as IJobSkillBook,
  321: b321 as unknown as IJobSkillBook,
  322: b322 as unknown as IJobSkillBook,
  400: b400 as unknown as IJobSkillBook,
  410: b410 as unknown as IJobSkillBook,
  411: b411 as unknown as IJobSkillBook,
  412: b412 as unknown as IJobSkillBook,
  420: b420 as unknown as IJobSkillBook,
  421: b421 as unknown as IJobSkillBook,
  422: b422 as unknown as IJobSkillBook,
  500: b500 as unknown as IJobSkillBook,
  510: b510 as unknown as IJobSkillBook,
  511: b511 as unknown as IJobSkillBook,
  512: b512 as unknown as IJobSkillBook,
  520: b520 as unknown as IJobSkillBook,
  521: b521 as unknown as IJobSkillBook,
  522: b522 as unknown as IJobSkillBook,
  1100: b1100 as unknown as IJobSkillBook,
  1110: b1110 as unknown as IJobSkillBook,
  1111: b1111 as unknown as IJobSkillBook,
  1200: b1200 as unknown as IJobSkillBook,
  1210: b1210 as unknown as IJobSkillBook,
  1211: b1211 as unknown as IJobSkillBook,
  1300: b1300 as unknown as IJobSkillBook,
  1310: b1310 as unknown as IJobSkillBook,
  1311: b1311 as unknown as IJobSkillBook,
  1400: b1400 as unknown as IJobSkillBook,
  1410: b1410 as unknown as IJobSkillBook,
  1411: b1411 as unknown as IJobSkillBook,
  1500: b1500 as unknown as IJobSkillBook,
  1510: b1510 as unknown as IJobSkillBook,
  1511: b1511 as unknown as IJobSkillBook,
}
